# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Salon
description: > # this means to ignore newlines until "baseurl:"
  Web home for Ferndale, Michigan based hairdresser John Niebauer currently based out of Fern and Dale's. John specializes in weddings, colorings, up-dos and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
theme-color: "#378ddd" # theme color for meta tag in head & favicons
ga-id: "UA-71260883-4" # Google Analytics ID

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap